# Generated by Django 5.1.4 on 2024-12-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bpm', models.IntegerField()),
                ('key', models.CharField(max_length=10)),
                ('cover_art', models.ImageField(upload_to='beats/covers/')),
                ('audio_file', models.FileField(upload_to='beats/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
